import fs from 'fs'
import path from 'path'
import { homedir, platform } from 'os'
import readline from 'readline'
import { lkPath } from '../lib/context.js'
import { clearLicense } from '../lib/license.js'
import { config } from '../lib/config.js'
function getConfigDir(){const h=homedir();switch(platform()){case 'darwin':return path.join(h,'Library','Preferences','lk-nodejs');case 'win32':return path.join(process.env.APPDATA||path.join(h,'AppData','Roaming'),'lk-nodejs');default:return path.join(process.env.XDG_CONFIG_HOME||path.join(h,'.config'),'lk-nodejs')}}
function getLicenseDir(){const h=homedir();switch(platform()){case 'darwin':return path.join(h,'Library','Preferences','lk-license-nodejs');case 'win32':return path.join(process.env.APPDATA||path.join(h,'AppData','Roaming'),'lk-license-nodejs');default:return path.join(process.env.XDG_CONFIG_HOME||path.join(h,'.config'),'lk-license-nodejs')}}
const CD=getConfigDir(),LD=getLicenseDir(),DF=path.join(homedir(),'.lk-device'),LG=path.join(homedir(),'.lk')
async function confirm(msg){const r=readline.createInterface({input:process.stdin,output:process.stdout});return new Promise(res=>{r.question(`${msg} (y/N): `,ans=>{r.close();res(ans.toLowerCase()==='y')})})}
function removeDir(d,lbl){if(fs.existsSync(d)){fs.rmSync(d,{recursive:true,force:true});console.log(`  ✓ Removed ${lbl}`);return true}console.log(`  - ${lbl} (not found)`);return false}
function removeFile(f,lbl){if(fs.existsSync(f)){fs.unlinkSync(f);console.log(`  ✓ Removed ${lbl}`);return true}console.log(`  - ${lbl} (not found)`);return false}
export async function clean(opts){const {context,license,cfg,device,logs,all,yes}=opts;if(!context&&!license&&!cfg&&!device&&!logs&&!all){console.log('lk clean - Remove lk data\n');console.log('Usage: lk clean [opts]\n');console.log('Options:');console.log('  -c, --context   Remove project .lk/ folder');console.log('  -l, --license   Clear license data');console.log('  -C, --config    Clear configuration (API keys, settings)');console.log('  -d, --device    Remove device ID');console.log('  --logs          Remove debug logs');console.log('  -a, --all       Remove everything');console.log('  -y, --yes       Skip confirmation');return}const ts=[];if(all||context)ts.push('Project context (.lk/)');if(all||license)ts.push('License data');if(all||cfg)ts.push('Configuration');if(all||device)ts.push('Device ID');if(all||logs)ts.push('Debug logs');console.log('Will remove:');ts.forEach(x=>console.log(`  • ${x}`));console.log('');if(!yes){const cnf=await confirm('Continue?');if(!cnf){console.log('Cancelled.');return}console.log('')}console.log('Cleaning...');if(all||context){const c=process.cwd();const ld=lkPath(c);removeDir(ld,'project context (.lk/)')}if(all||license){clearLicense();removeDir(LD,'license store')}if(all||cfg){config.clear();removeDir(CD,'config store')}if(all||device){removeFile(DF,'device ID')}if(all||logs){removeDir(LG,'debug logs')}console.log('\nDone.')}